# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xGG4MkUw4nyswKORzh_FKlAtyv-QQiVq
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ai_content_ideator.py
# import streamlit as st
# import google.generativeai as genai
# 
# st.set_page_config(page_title="AI Content Ideator", page_icon="🧠")
# st.title("🧠 AI Content Ideator")
# st.caption("Generate viral content ideas, hooks, and captions instantly.")
# 
# api_key = "AIzaSyCGNWs_OHNkUnO72fzS4zZx6nTo3_j7Bs0"
# genai.configure(api_key=api_key)
# 
# topic = st.text_input("Enter your niche or theme (e.g. AI, self-growth, finance):")
# 
# if st.button("Generate Ideas"):
#     if not topic:
#         st.warning("Please enter a topic first.")
#     else:
#         prompt = f"Generate 3 unique content ideas, 3 hooks, and 3 captions for the niche '{topic}'. Make them sound human, engaging, and viral-worthy."
#         model = genai.GenerativeModel("gemini-1.5-flash")
#         response = model.generate_content(prompt)
#         st.subheader("Generated Ideas:")
#         st.write(response.text)
#

!streamlit run ai_content_ideator.py

!pip install streamlit

!streamlit run ai_content_ideator.py

!ls

from google.colab import files
files.download("ai_content_ideator.py")